In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_Columns', None)
pd.set_option('display.max_rows', None)

In [3]:
cr = pd.read_csv(r"CreditRisk.csv")

In [5]:
cr.head(10)

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   
5  LP001011   Male     Yes         2.0      Graduate           Yes   
6  LP001013   Male     Yes         0.0  Not Graduate            No   
7  LP001014   Male     Yes         4.0      Graduate            No   
8  LP001018   Male     Yes         2.0      Graduate            No   
9  LP001020   Male     Yes         1.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   
6             2333             1516.0        95.0             360.0   
7             3036             2504.0       158.0             360.0   
8             4006             1526.0       168.0             360.0   
9            12841            10968.0       349.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

In [7]:
cr.shape

(981, 13)

In [9]:
cr.isnull().sum()

Loan_ID               0
Gender               24
Married               3
Dependents           25
Education             0
Self_Employed        55
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           27
Loan_Amount_Term     20
Credit_History       79
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
cr.Gender = cr.Gender.fillna('Male')
cr.Married = cr.Married.fillna('No')
cr.Dependents = cr.Dependents.fillna(0)
cr.Self_Employed = cr.Self_Employed.fillna('Yes')
cr.LoanAmount = cr.LoanAmount.fillna(cr.LoanAmount.mean())
cr.Loan_Amount_Term = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())
cr.Credit_History = cr.Credit_History.fillna(0)

In [13]:
cr.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [15]:
cr = cr.drop(['Loan_ID'], axis = 1)

In [17]:
cr.shape

(981, 12)

In [19]:
cr.Loan_Status = cr.Loan_Status.replace({'Y':1, 'N':0})

C:\Users\om\AppData\Local\Temp\ipykernel_10984\4226850886.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cr.Loan_Status = cr.Loan_Status.replace({'Y':1, 'N':0})


In [21]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             981 non-null    object 
 1   Married            981 non-null    object 
 2   Dependents         981 non-null    float64
 3   Education          981 non-null    object 
 4   Self_Employed      981 non-null    object 
 5   ApplicantIncome    981 non-null    int64  
 6   CoapplicantIncome  981 non-null    float64
 7   LoanAmount         981 non-null    float64
 8   Loan_Amount_Term   981 non-null    float64
 9   Credit_History     981 non-null    float64
 10  Property_Area      981 non-null    object 
 11  Loan_Status        981 non-null    int64  
dtypes: float64(5), int64(2), object(5)
memory usage: 92.1+ KB


In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [24]:
cr[cr.select_dtypes(include=['object']).columns] = cr[cr.select_dtypes(include=['object']).columns].apply(le.fit_transform)

In [25]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             981 non-null    int32  
 1   Married            981 non-null    int32  
 2   Dependents         981 non-null    float64
 3   Education          981 non-null    int32  
 4   Self_Employed      981 non-null    int32  
 5   ApplicantIncome    981 non-null    int64  
 6   CoapplicantIncome  981 non-null    float64
 7   LoanAmount         981 non-null    float64
 8   Loan_Amount_Term   981 non-null    float64
 9   Credit_History     981 non-null    float64
 10  Property_Area      981 non-null    int32  
 11  Loan_Status        981 non-null    int64  
dtypes: float64(5), int32(5), int64(2)
memory usage: 72.9 KB


#Sampling

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
cr_train, cr_test = train_test_split(cr, test_size= 0.2)

In [34]:
cr_train_x = cr_train.iloc[: , 0:-1]
cr_train_y = cr_train.iloc[: , -1]

cr_test_x = cr_test.iloc[: , 0:-1]
cr_test_y = cr_test.iloc[: , -1]

In [36]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(cr_train_x, cr_train_y)

DecisionTreeClassifier()

In [38]:
dec_pred = dtree.predict(cr_test_x)
dec_pred.shape

(197,)

In [40]:
from sklearn.metrics import confusion_matrix

In [42]:
dtree_tab = confusion_matrix(cr_test_y , dec_pred)
dtree_tab

array([[ 36,  24],
       [ 30, 107]], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(cr_test_y, dec_pred)

0.7258883248730964

In [45]:
#Feature importance

In [46]:
dtree.feature_importances_

array([0.03002153, 0.03063317, 0.03638301, 0.02477293, 0.01103435,
       0.23038791, 0.0910676 , 0.20226777, 0.06157524, 0.24834246,
       0.03351403])

In [47]:
dtree.feature_importances_.sum()

0.9999999999999999

In [50]:
#Higher the value of feature importance more important or significant that variable or feature is

In [54]:
cr_train_x.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [56]:
feature_imp = pd.DataFrame({'Feature': cr_train_x.columns, 'Importance': dtree.feature_importances_ })
feature_imp

Feature  Importance
0              Gender    0.030022
1             Married    0.030633
2          Dependents    0.036383
3           Education    0.024773
4       Self_Employed    0.011034
5     ApplicantIncome    0.230388
6   CoapplicantIncome    0.091068
7          LoanAmount    0.202268
8    Loan_Amount_Term    0.061575
9      Credit_History    0.248342
10      Property_Area    0.033514

In [58]:
feature_imp.sort_values('Importance', ascending=False)

Feature  Importance
9      Credit_History    0.248342
5     ApplicantIncome    0.230388
7          LoanAmount    0.202268
6   CoapplicantIncome    0.091068
8    Loan_Amount_Term    0.061575
2          Dependents    0.036383
10      Property_Area    0.033514
1             Married    0.030633
0              Gender    0.030022
3           Education    0.024773
4       Self_Employed    0.011034

In [60]:
cr_train,cr_test = train_test_split(cr, test_size=.2)

In [62]:
cr_train_x = cr_train.iloc[:, [9,5,7,6,10,2,8]]
cr_train_y = cr_train.iloc[:,-1]

cr_test_x = cr_test.iloc[:, [9,5,7,6,10,2,8]]
cr_test_y = cr_test.iloc[:,-1]


In [64]:
cr_test_x.head()

Credit_History  ApplicantIncome  LoanAmount  CoapplicantIncome  \
300             0.0             1800        93.0             2934.0   
958             1.0             6858       176.0                0.0   
323             0.0             3166       132.0             2985.0   
30              0.0             4166       201.0             3369.0   
343             1.0             3173        74.0                0.0   

     Property_Area  Dependents  Loan_Amount_Term  
300              2         0.0             360.0  
958              0         0.0             360.0  
323              0         0.0             360.0  
30               2         1.0             360.0  
343              1         4.0             360.0

In [66]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier( criterion='entropy', max_depth=7, min_samples_split=40,class_weight='balanced')

In [68]:
dtree.fit(cr_train_x, cr_train_y)

DecisionTreeClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=7, min_samples_split=40)

In [70]:
dec_pred = dtree.predict(cr_test_x)
dec_pred

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      dtype=int64)

In [72]:
confusion_matrix(cr_test_y, dec_pred)

array([[ 43,  18],
       [ 33, 103]], dtype=int64)

In [74]:
accuracy_score(cr_test_y, dec_pred)

0.7411167512690355

In [76]:
from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
import pydot

In [78]:
dot_data = StringIO()

In [80]:
export_graphviz(dtree, out_file = dot_data, filled=True, rounded=True, special_characters=True, feature_names = cr_train_x.columns)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())

(graph, ) = pydot.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())

FileNotFoundError: [WinError 2] "dot" not found in path.