In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
print(a[1:7:2])

[2 4 6]


In [4]:
a = np.array([[1,2,3], [4,5,6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[0,0]

1

In [7]:
a = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a[1:2, 1:2]

array([[5]])

In [10]:
a[0:3, 0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [15]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b[:, -3]

array([1, 4])

In [22]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
b = np.append(a,[[5,6]], axis=0)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
np.mean(a)

2.5

In [28]:
np.median(a)

2.5

In [29]:
np.std(a)

1.118033988749895