In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)
pd.set_option('display.max_row',None)

In [2]:
s = pd.read_csv(r'svmfile.csv')

In [3]:
s.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  duration  campaign  pdays  previous     poutcome  \
0   may         mon       261         1    999         0  nonexistent   
1   may         mon       149         1    999         0  nonexistent   
2   may         mon       226         1    999         0  nonexistent   
3   may         mon       151         1    999         0  nonexistent   
4   may         mon       307         1    999         0  nonexistent   

   emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0           1.1          93.994          -36.4      4.857       5191.0  no  
1           1.1          93.994          -36.4      4.857       5191.0  no  
2           1.1          93.994          -36.4      4.857       5191.0  no  
3           1.1          93.994          -36.4      4.857       5191.0  no  
4           1.1          93.994          -36.4      4.857       5191.0  no

In [4]:
s.shape

(41188, 21)

In [5]:
s.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [6]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
s.marital.value_counts()

marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

In [9]:
s.job = le.fit_transform(s.job)
s.marital = le.fit_transform(s.marital)
s['cons.conf.idx'] = le.fit_transform(s['cons.conf.idx'])
s['emp.var.rate'] = le.fit_transform(s['emp.var.rate'])

In [10]:
s.education.value_counts()

education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

In [11]:
s.education.replace({'illiterate':0 , 'unknown':0 , 'basic.6y': 1  , 'basic.4y':2 , 'basic.9y':3, 'high.school': 4 , 'university.degree':5 ,  'professional.course':6}, inplace=True)

C:\Users\om\AppData\Local\Temp\ipykernel_2368\2299346494.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.education.replace({'illiterate':0 , 'unknown':0 , 'basic.6y': 1  , 'basic.4y':2 , 'basic.9y':3, 'high.school': 4 , 'university.degree':5 ,  'professional.course':6}, inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\2299346494.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=Fal

In [12]:
s.default.value_counts()

default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64

In [13]:
s.default.replace({'unknown':0 , 'no':1 , 'yes':2} , inplace=True)

C:\Users\om\AppData\Local\Temp\ipykernel_2368\3758030938.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.default.replace({'unknown':0 , 'no':1 , 'yes':2} , inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\3758030938.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s.default.repla

In [14]:
s.housing.value_counts()

housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64

In [15]:
s.housing.replace({'unknown':0 , 'no':1 , 'yes':2} , inplace=True)

C:\Users\om\AppData\Local\Temp\ipykernel_2368\2562319022.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.housing.replace({'unknown':0 , 'no':1 , 'yes':2} , inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\2562319022.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s.housing.repla

In [16]:
s.loan.value_counts()

loan
no         33950
yes         6248
unknown      990
Name: count, dtype: int64

In [17]:
s.loan.replace({'unknown':0 , 'no':1 , 'yes':2} , inplace=True)

C:\Users\om\AppData\Local\Temp\ipykernel_2368\3536411632.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.loan.replace({'unknown':0 , 'no':1 , 'yes':2} , inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\3536411632.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s.loan.replace({'u

In [18]:
s.contact.value_counts()

contact
cellular     26144
telephone    15044
Name: count, dtype: int64

In [19]:
s.contact = le.fit_transform(s.contact)

In [20]:
s.month.value_counts()

month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
apr     2632
oct      718
sep      570
mar      546
dec      182
Name: count, dtype: int64

In [21]:
s.month.replace({'mar':3 , 'apr':4 , 'may':5 , 'jun':6 , 'jul':7 , 'aug':8 , 'sep':9 , 'oct':10 , 'nov':11 , 'dec':12}, inplace=True)       

C:\Users\om\AppData\Local\Temp\ipykernel_2368\3361367045.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.month.replace({'mar':3 , 'apr':4 , 'may':5 , 'jun':6 , 'jul':7 , 'aug':8 , 'sep':9 , 'oct':10 , 'nov':11 , 'dec':12}, inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\3361367045.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.

In [22]:
s.poutcome.value_counts()

poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64

In [23]:
s.poutcome.replace({'nonexistent':0 , 'failure':1 , 'success':2}, inplace = True) 

C:\Users\om\AppData\Local\Temp\ipykernel_2368\1774660200.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.poutcome.replace({'nonexistent':0 , 'failure':1 , 'success':2}, inplace = True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\1774660200.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  

In [24]:
s.day_of_week.value_counts()

day_of_week
thu    8623
mon    8514
wed    8134
tue    8090
fri    7827
Name: count, dtype: int64

In [25]:
s.day_of_week.replace({'mon':1 , 'tue':2 , 'wed':3 , 'thu':4 , 'fri':5 }, inplace=True)

C:\Users\om\AppData\Local\Temp\ipykernel_2368\1067568179.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.day_of_week.replace({'mon':1 , 'tue':2 , 'wed':3 , 'thu':4 , 'fri':5 }, inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\1067568179.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', Tru

In [26]:
s.y.value_counts()

y
no     36548
yes     4640
Name: count, dtype: int64

In [27]:
s.y.replace({'no':0 , 'yes':1}, inplace=True)

C:\Users\om\AppData\Local\Temp\ipykernel_2368\2354929191.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  s.y.replace({'no':0 , 'yes':1}, inplace=True)
C:\Users\om\AppData\Local\Temp\ipykernel_2368\2354929191.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  s.y.replace({'no':0 , 'yes':1}, inpl

In [28]:
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  int32  
 2   marital         41188 non-null  int32  
 3   education       41188 non-null  int64  
 4   default         41188 non-null  int64  
 5   housing         41188 non-null  int64  
 6   loan            41188 non-null  int64  
 7   contact         41188 non-null  int32  
 8   month           41188 non-null  int64  
 9   day_of_week     41188 non-null  int64  
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  int64  
 15  emp.var.rate    41188 non-null  int64  
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [29]:
from sklearn.model_selection import train_test_split
s_train , s_test = train_test_split(s, test_size = .2)

In [36]:
df1 = s_train[s_train_y==1]   #OverSampling
df1.shape

(3713, 21)

In [38]:
s_train = pd.concat([s_train , df1, df1, df1])

In [34]:
s_train_x = s_train.iloc[:, 0:-1]
s_train_y = s_train.iloc[:,-1]

s_test_x = s_test.iloc[:, 0:-1]
s_test_y = s_test.iloc[:,-1]


In [40]:
from sklearn.naive_bayes import MultinomialNB
ct_s = MultinomialNB()

In [42]:
ct_s.fit(s_train_x, s_train_y)

MultinomialNB()

In [44]:
#s_train_x.head(45)

In [46]:
pred_ct = ct_s.predict(s_test_x)
pred_ct

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [48]:
from sklearn.metrics import confusion_matrix
confusion_matrix(s_test_y , pred_ct)

array([[6270, 1041],
       [ 281,  646]], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(s_test_y , pred_ct)

0.8395241563486283

In [65]:
from sklearn.svm import SVC
svc_s = SVC(kernel = 'linear' , degree=5)

In [67]:
svc_s.fit(s_train_x , s_train_y)

SVC(degree=5, kernel='linear')

In [68]:
pred_svc = svc_s.predict(s_test_x)
pred_svc

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [69]:
confusion_matrix(s_test_y, pred_svc)

array([[6631,  680],
       [ 325,  602]], dtype=int64)

In [70]:
accuracy_score(s_test_y , pred_svc)

0.8780043699927167