In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2.0,3,4,5])

array([1., 2., 3., 4., 5.])

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b = np.array([[1,2,3],[4,5,6]], dtype=int)

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(b)

numpy.ndarray

In [11]:
b[1][2] #[1] row , [2] column

6

In [14]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(1,26,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
num = np.linspace(1,10,100) # it create 1 to 10 in 100 intervals

In [26]:
num

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [27]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [28]:
b.shape

(3, 3)

In [29]:
c = np.array([1,2,3,4,5,6,7,8,9])

In [30]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
c.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
c.max()

9

In [33]:
c.min()

1

In [36]:
c.argmax() # give the index count which have greater value

8

In [37]:
c.argmin()

0

In [38]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b.transpose() # Convert Rows to col.& cols to rows

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
np.sqrt(6)

2.449489742783178

In [42]:
np.square(45)

2025

In [43]:
np.add(45,45)

90

In [44]:
np.log(3)

1.0986122886681098

In [45]:
np.log10(100)

2.0