In [5]:
import pandas as pd
import numpy as np 
pd.set_option('display.max_columns',None)
pd.set_option('display.max_row',None)

In [7]:
ctg = pd.read_csv(r'CTG.csv')

In [11]:
ctg.head()

LB     AC   FM  NSP
0  120  0.000  0.0    2
1  132  0.006  0.0    1
2  133  0.003  0.0    1
3  134  0.003  0.0    1
4  132  0.007  0.0    1

In [13]:
ctg.isnull().sum()

LB     0
AC     0
FM     0
NSP    0
dtype: int64

In [15]:
ctg.shape

(2126, 4)

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
ctg[ctg.select_dtypes(include=['object']).columns] = ctg[ctg.select_dtypes(include=['object']).columns].apply(le.fit_transform)

In [23]:
ctg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   LB      2126 non-null   int64  
 1   AC      2126 non-null   float64
 2   FM      2126 non-null   float64
 3   NSP     2126 non-null   int64  
dtypes: float64(2), int64(2)
memory usage: 66.6 KB


In [25]:
# SAmpling

In [27]:
from sklearn.model_selection import train_test_split
ctg_train, ctg_test = train_test_split(ctg, test_size = .2)

In [29]:
ctg_train_x = ctg_train.iloc[:,0:-1]
ctg_train_y = ctg_train.iloc[:,-1]

ctg_test_x = ctg_test.iloc[:,0:-1]
ctg_test_y = ctg_test.iloc[:,-1]

In [67]:
# Decision Tree

In [33]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(ctg_train_x,ctg_train_y)

DecisionTreeClassifier()

In [35]:
dec_pred = dtree.predict(ctg_test_x)
dec_pred

array([1, 1, 1, 1, 3, 2, 3, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 3,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 3, 3, 1, 2, 1, 1, 1, 1, 3, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 3, 3, 1,
       1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 2, 3, 1, 2, 1, 1, 1, 2, 1,

In [37]:
#Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix

In [41]:
dtree_tab = confusion_matrix(ctg_test_y, dec_pred)
dtree_tab

array([[311,  15,  11],
       [ 20,  27,   5],
       [ 19,   5,  13]], dtype=int64)

In [43]:
# Accuracy

In [45]:
from sklearn.metrics import accuracy_score
accuracy_score(ctg_test_y , dec_pred)

0.823943661971831

In [48]:
# random Forest

In [58]:
from sklearn.ensemble import RandomForestClassifier
ran_for = RandomForestClassifier(n_estimators=50,criterion='gini')
ran_for.fit(ctg_train_x , ctg_train_y)

RandomForestClassifier(n_estimators=50)

In [60]:
pred_ran = ran_for.predict(ctg_test_x)
pred_ran

array([1, 1, 1, 1, 3, 2, 3, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2,
       1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 3,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 3, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 2, 3, 1, 2, 1, 1, 1, 1, 3, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 3, 1,
       1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 2, 3, 1, 2, 1, 3, 1, 2, 1,

In [62]:
tab_ran = confusion_matrix(ctg_test_y , pred_ran)
tab_ran

array([[307,  16,  14],
       [ 19,  28,   5],
       [ 15,   6,  16]], dtype=int64)

In [64]:
accuracy_score(ctg_test_y , pred_ran)

0.823943661971831